# Generated by Django 5.2.14 on 2026-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('speaker', models.CharField(max_length=100)),
                ('bible_verse', models.CharField(blank=True, help_text='e.g., John 3:16', max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermon_files/audio/')),
                ('video_link', models.URLField(blank=True, help_text='YouTube or other video link')),
                ('document', models.FileField(blank=True, null=True, upload_to='sermon_files/documents/')),
                ('series', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
