# Generated by Django 5.1.4 on 2026-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Grace Community Church', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Short tagline or mission statement', max_length=300)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='church_logos/')),
                ('description', models.TextField(blank=True, help_text='About the church')),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('service_times', models.TextField(blank=True, help_text='Service schedule/timings')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church Information',
                'verbose_name_plural': 'Church Information',
            },
        ),
    ]
