# Generated by Django 5.1.4 on 2026-06-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_churchinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchinfo',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=100, verbose_name='Twilio Account SID'),
        ),
        migrations.AddField(
            model_name='churchinfo',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Twilio Auth Token'),
        ),
        migrations.AddField(
            model_name='churchinfo',
            name='twilio_whatsapp_from',
            field=models.CharField(blank=True, help_text='Twilio WhatsApp-enabled number e.g. +14155238886', max_length=20, verbose_name='WhatsApp Sender Number'),
        ),
    ]
