# Generated by Django 5.2.14 on 2026-05-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_type', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('first_fruits', 'First Fruits'), ('thanksgiving', 'Thanksgiving'), ('building_fund', 'Building Fund'), ('mission', 'Mission'), ('special', 'Special Contribution'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money'), ('online', 'Online Payment')], default='cash', max_length=30)),
                ('receipt_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='members.member')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
