# Generated by Django 5.2.14 on 2026-05-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('request', models.TextField(help_text='Your prayer request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('prayed', 'Prayed For'), ('answered', 'Answered'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin/Pastor notes')),
                ('is_private', models.BooleanField(default=False, help_text='Keep this request private')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
