# Generated by Django 5.1.4 on 2026-06-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_voter',
            field=models.BooleanField(default=False, verbose_name='Registered Voter'),
        ),
        migrations.AddField(
            model_name='member',
            name='voter_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Voter ID / EPIC'),
        ),
    ]
