# Generated by Django 5.1.4 on 2026-06-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_is_voter_member_voter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaptismCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('baptism_date', models.DateField()),
                ('baptism_type', models.CharField(choices=[('water', 'Water Baptism'), ('holy_spirit', 'Holy Spirit Baptism'), ('both', 'Both'), ('none', 'None')], default='water', max_length=20)),
                ('officiated_by', models.CharField(blank=True, max_length=200, verbose_name='Officiated By (Pastor)')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baptism_certificates', to='members.member')),
            ],
            options={
                'verbose_name': 'Baptism Certificate',
                'verbose_name_plural': 'Baptism Certificates',
                'ordering': ['-baptism_date'],
            },
        ),
    ]
