# Generated by Django 5.1.4 on 2026-06-02 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_baptismcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
