# Generated by Django 5.2.14 on 2026-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sunday_service', 'Sunday Service'), ('prayer_meeting', 'Prayer Meeting'), ('bible_study', 'Bible Study'), ('youth_meeting', 'Youth Meeting'), ('choir_practice', 'Choir Practice'), ('cell_group', 'Cell Group'), ('other', 'Other')], max_length=30)),
                ('date', models.DateField()),
                ('attended', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'member__first_name'],
            },
        ),
    ]
