# Generated by Django 5.2.14 on 2026-05-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.member'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'event_type', 'date')},
        ),
    ]
