# Generated by Django 5.1.4 on 2026-06-02 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('members', '0003_member_is_voter_member_voter_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'staff__first_name']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.staff'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='member',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('staff', 'event_type', 'date')},
        ),
    ]
